version: "3"

services:
  jupyterlab:
    container_name: jupyterlab
    restart: always
    environment:
      USER: hoge
      PASSWD: passowrd
    build:
      context:
        ./work
      args:
        USER: "hoge"
        PASSWD: "hoge"
    # user: root
    tty: true

    network_mode: "host"
    volumes:
      - "./work:/home/${USER}/work"
    command: jupyter-lab --no-browser
