version: "3"

volumes:
  src:
    external: 
      name: src

services:
  jupyterlab:
    container_name: jupyterlab
    restart: always
    environment:
      USER: hoge
      PASSWD: password
    build:
      context: ../
      dockerfile: python-for-beginner/Docker/Dockerfile
      args:
        USER: "hoge"
        PASSWD: "hoge"
    # user: root
    tty: true

    network_mode: "host"
    volumes:
      - "src:/home/${USER}/src"
    command: jupyter-lab --no-browser
