version: "3"

services:
  jupyterlab:
    container_name: jupyterlab
    restart: always
    build: ./work
    user: root
    # working_dir: '/work'
    tty: true
    # ports:
    #   - "127.0.0.1:8888:8888"
    network_mode: "host"
    volumes:
      - "./work:/root/work"
    command: jupyter-lab --allow-root --no-browser
